#!/bin/bash

# Created by JHStewman - October 2011
# This is setup for the basic structure of a Mac Application folder
# The runtines runDarwin and darwin are in the Content/MacOS folder
# The rest of the structure is similar to that on the Windows platform
# and places all data within a common folder structure so that the
# application can be run from anywhere, including an external drive  

pgmName=$(basename "$0")
pgmStartDir=$(dirname "$0")

if [ "$BASH_SOURCE" != "./darwinMac" ] 
then
   # must have been clicked from Finder
   echo Run from Finder or Shortcut to darwinMac.app - using app location as DARWINHOME
	# echo $BASH_SOURCE
	home=`echo $BASH_SOURCE | sed s/darwinMac//3`
	if [ "$home" != "$BASH_SOURCE" ]
	then
		# must have stripped the last even in a path containing darwinMac 3 times
		# prevents problem of running pgm from inside installer
		export DARWINHOME="$home"
   else
		# should work as previously 
		export DARWINHOME=`echo $BASH_SOURCE | sed s/darwinMac//2`
	fi
else
   # must have been started from command line
   if [ -z "$DARWINHOME" ] 
   then  
      echo Started from command line - using pwd as DARWINHOME
      export DARWINHOME=`pwd`
   else
      echo DARWINHOME is already defined as $DARWINHOME
   fi
fi

# if all else fails
if [ x"$DARWINHOME" == "x" ]
then 
   export DARWINHOME="$pgmStartDir"
fi

echo darwinHome=$DARWINHOME
export DYLD_FALLBACK_LIBRARY_PATH=../lib
export GDK_PIXBUF_MODULE=../lib/gdk-pixbuf-2.0/2.10.0
export GDK_PIXBUF_MODULE_FILE=$GDK_PIXBUF_MODULE/loaders.cache
export PATH=.:$DARWINHOME/system/bin:$PATH
cd "$DARWINHOME/system/bin" 
exec darwin &

